### ISSUE TITLE
Server 500 error: http://usidawebdev01:81/USGDNRWebAPI/api/v1/accounts/489204

### ISSUE THREAD

**Issue by webdevusic** [webdevusic/udr#2]
**Recommended debugging approach from Howard**:
      Investigate ExperianReportData values for all policies associated with the ClientId.

**Root Cause**:
PROCEDURE [dbo].[spUDR_GetAccountDetailsByClientId]
	(SELECT b_year_business_started FROM Experian.dbo.GetExperianReportData(a.Policy_NBR)) as 'YearsInBusiness',
ExceptionMessage: "colname=YearsInBusiness;targettype=System.Int32;value= .Input string was not in a correct format.",

In USGPDW environment, this returns zero rows
In USGDDW environment, this returns 1 row, with value = ' '
SELECT b_year_business_started FROM Experian.dbo.GetExperianReportData(4675745)
------------------------------------------------

**AccountController.cs:line 54**

--------------------------------------------
Object
config
:
Object
headers
:
Object
method
:
"GET"
paramSerializer
:
ngParamSerializer(params)
transformRequest
:
Array[1]
transformResponse
:
Array[1]
url
:
"http://usidawebdev01:81/USGDNRWebAPI/api/v1/accounts/489204"
__proto__
:
Object
data
:
Object
ExceptionMessage
:
"Input string was not in a correct format."
ExceptionType
:
"System.FormatException"
Message
:
"An error has occurred."
StackTrace
:
"   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
↵   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
↵   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
↵   at DocumentationReferral.Services.Data.DTO.BaseConverter.Parse(DataRow row, Object entity) in c:\Program Files (x86)\Jenkins\jobs\DocumentationReferral - Web API - Main\workspace\DocumentationReferral.Services.Data\DTO\BaseConverter.cs:line 19
↵   at DocumentationReferral.Services.Data.DTO.DataTableToModel.AsSingle[T](DataTable resultTable) in c:\Program Files (x86)\Jenkins\jobs\DocumentationReferral - Web API - Main\workspace\DocumentationReferral.Services.Data\DTO\DataTableToModel.cs:line 17
↵   at DocumentationReferral.Services.Data.Repositories.Concrete.BaseRepository`1.<Single>d__3.MoveNext() in c:\Program Files (x86)\Jenkins\jobs\DocumentationReferral - Web API - Main\workspace\DocumentationReferral.Services.Data\Repositories\Concrete\BaseRepository.cs:line 51
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
↵   at DocumentationReferral.Services.Data.Repositories.Concrete.AccountRepository.<GetAccountByClientId>d__8.MoveNext() in c:\Program Files (x86)\Jenkins\jobs\DocumentationReferral - Web API - Main\workspace\DocumentationReferral.Services.Data\Repositories\Concrete\AccountRepository.cs:line 59
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
↵   at DocumentationReferral.Services.REST.Controllers.AccountController.<Get>d__3.MoveNext() in c:\Program Files (x86)\Jenkins\jobs\DocumentationReferral - Web API - Main\workspace\DocumentationReferral.Services.REST\Controllers\AccountController.cs:line 54
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
↵   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
__proto__
:
Object
headers
:
(name)
status
:
500
statusText
:
"Internal Server Error"

**Comment by webdevusic** [comment]
Issue corrected in development environment, and T-SQL code works correctly in Test environment.

Solution:
In procedure **[dbo].[spUDR_GetAccountDetailsByClientId]**
**Changed**:
(SELECT b_year_business_started FROM Experian.dbo.GetExperianReportData(a.Policy_NBR) as 'YearsInBusiness', 

**...to...**
(SELECT b_year_business_started FROM Experian.dbo.GetExperianReportData(a.Policy_NBR) **WHERE ISNUMERIC(b_year_business_started) = 1)** as 'YearsInBusiness',
